<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFramework>net35</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>CadAutoCloudNote.R17</RootNamespace>
    <AssemblyName>CadAutoCloudNote_R17</AssemblyName>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
    <OutputPath>..\..\build\R17\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>false</UseWPF>
    <EnableWPF>false</EnableWPF>
    
    <DefineConstants>$(DefineConstants);CAD_R17;USE_CONFIGFORM</DefineConstants>
    <SatelliteResourceLanguages>en-US;zh-Hans</SatelliteResourceLanguages>
    <Platforms>AnyCPU;x86</Platforms>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <Import Project="..\..\CadAutoCloudNote.Core\CadAutoCloudNote.Core.projitems" Label="Shared" />

  <ItemGroup>
    <Reference Include="AcDbMgd">
      <HintPath>..\..\Libs\AutoCAD\Net2.0_2007-2009\AcDbMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcMgd">
      <HintPath>..\..\Libs\AutoCAD\Net2.0_2007-2009\AcMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>

    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

</Project>
