<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net45</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>CadAutoCloudNote.R20</RootNamespace>
    <AssemblyName>CadAutoCloudNote_R20</AssemblyName>
    
    <OutputPath>..\..\build\R20\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    
    <DefineConstants>$(DefineConstants);CAD_R20;USE_WPF</DefineConstants>
    <SatelliteResourceLanguages>en-US;zh-Hans</SatelliteResourceLanguages>
    <Platforms>AnyCPU;x86;x64</Platforms>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <Import Project="..\..\CadAutoCloudNote.Core\CadAutoCloudNote.Core.projitems" Label="Shared" />

  <ItemGroup>
    <Reference Include="AcCoreMgd">
      <HintPath>..\..\Libs\AutoCAD\Net4.5_2015-2016\accoremgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcDbMgd">
      <HintPath>..\..\Libs\AutoCAD\Net4.5_2015-2016\acdbmgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcMgd">
      <HintPath>..\..\Libs\AutoCAD\Net4.5_2015-2016\acmgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
